namespace: monk-mysql-proxysql-monitor

stack:
  defines: process-group

  runnable-list:
    - monk-mysql-proxysql-monitor/master
    - monk-mysql-proxysql-monitor/slave1
    - monk-mysql-proxysql-monitor/slave2
    - monk-mysql-proxysql-monitor/lb
    - monk-mysql-proxysql-monitor/configure
    - monk-mysql-proxysql-monitor/grafana
    - monk-mysql-proxysql-monitor/promethues
    - monk-mysql-proxysql-monitor/promethues-mysql-slave1-exporter
    - monk-mysql-proxysql-monitor/promethues-mysql-slave2-exporter
    - monk-mysql-proxysql-monitor/promethues-mysql-master-exporter

  variables:
    mysql_database_repl_user: "repl"
    mysql_database_repl_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_monitor_user: "monitor"
    mysql_database_monitor_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "monk"
    mysql_master_database_port: 3306
    mysql_slave1_database_port: 3307
    mysql_slave2_database_port: 3308
    mysql_database_password: "RhgDPXPEnAgxxXYZ"
    mysql_image_tag:
      value: 8.0
      type: string
    mysql_database_data_volume_path: /mnt/mysql
    mysql_database_data_volume_size: 60
    proxysql_admin_username: admin
    proxysql_admin_password: admin
