namespace:  monk-mysql

stack:
  defines: process-group

  runnable-list:
    -  monk-mysql/db

  variables:
    mysql_database_user:
      value: "db_user"
      type: string
    mysql_database_root_password:
      value: "RhgDPXPEnAgJ5q5g"
      type:  string
    mysql_database_name:
      value: "monk"
      type: string
    mysql_database_port:
      value: 3306
      type: int
    mysql_database_password:
      value: "RhgDPXPEnAgxxXYZ"
      type: string
    mysql_image_tag:
      value: "8.0"
      type: string
    mysql_database_data_volume_path:
      value: <- `${moncc-volume-path}/mysql`
      type: string
    mysql_database_data_volume_size:
      value: 60
      type: int
