---
namespace: monk-mysql-proxysql

stack:
  defines: process-group
  runnable-list:
    - monk-mysql-proxysql/master
    - monk-mysql-proxysql/slave1
    - monk-mysql-proxysql/slave2
    - monk-mysql-proxysql/configure
    - monk-mysql-proxysql/lb
  variables:
    mysql_database_repl_user:
      type: string
      value: repl
    mysql_database_repl_password:
      type: string
      value: RhgDPXPEnAgJ5q5g
    mysql_database_monitor_user:
      type: string
      value: monitor
    mysql_database_monitor_password:
      type: string
      value: RhgDPXPEnAgJ5q5g
    mysql_database_user:
      type: string
      value: db_user
    mysql_database_root_password:
      type: string
      value: RhgDPXPEnAgJ5q5g
    mysql_database_name:
      type: string
      value: monk
    mysql_master_database_port:
      type: int
      value: 3306
    mysql_slave1_database_port:
      type: int
      value: 3307
    mysql_slave2_database_port:
      type: int
      value: 3308
    mysql_database_password:
      type: string
      value: RhgDPXPEnAgxxXYZ
    mysql_image_tag:
      type: string
      value: '8.0'
    mysql_database_data_volume_path:
      value: <- `${moncc-volume-path}`
      type: string
    mysql_database_data_volume_size:
      type: int
      value: 60
    proxysql_admin_username:
      type: string
      value: admin
    proxysql_admin_password:
      type: string
      value: admin
